### ISSUE TITLE
can't use include funtion

### ISSUE THREAD

**Issue by HaiNguyen13** [emulienfou/dwoo#28]
Hi, I am using Dwoo for CI, but include function didn't work right, I used 
{include('my_file.php')}
it didn't include the my_file.php content, just displayed the file name. (my_file.php)

ex: 
index.php file content:
{include('my_file.php')}

my_file.php content:
ABC

when I enter the index.php:
my_file.php

every others functions worked but this. Please help.

**Comment by emulienfou** [comment]
Try somethink like that:

{include file="my_file.php"}
